- name: Add Elasticsearch APT key
  apt_key:
    url: 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch'
    id: '{{ filebeat_key_id }}'
    state: present

- name: Add Beats repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    state: present
    update_cache: True

- name: Install filebeat
  apt:
    package: filebeat
    state: present

- name: Creates ELK Cert Directory
  file:
    path: /etc/beat
    state: directory
    mode: 0755

- name: Install beat forwarder cert
  copy:
    src: "{{ elk_beat_forwarder_cert }}"
    dest: "/etc/beat/beat-forwarder.crt"

- name: Install forwarder key
  copy:
    src: "{{ elk_beat_forwarder_key }}"
    dest: "/etc/beat/beat-forwarder.key"

- name: Configure filebeat
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
  notify: Restart filebeat